services:
  neo4j:
    build: .
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,algo.*
      NEO4J_dbms_security_procedures_whitelist: apoc.*,algo.*
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_AUTH: neo4j/your_password
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: '["apoc", "apoc-extended"]'
    volumes:
      - ./volume/data:/data
      - ./volume/plugins:/plugins
      - ./volume/import:/import
      - ./seed:/seed
    networks:
      - neo4j-network

networks:
  neo4j-network:
    driver: bridge
