/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
export interface HadithChains {
  chapter_no?: number;
  hadith_no?: string;
  position?: number | null;
  scholar_indx?: number;
  source?: string;
}
export interface Hadiths {
  chapter: string;
  chapter_no: number;
  explanation?: string | null;
  hadith_id: number;
  hadith_no: string;
  id?: number;
  source: string;
  text_ar?: string | null;
  text_en?: string | null;
}
export interface Rawis {
  birth_date_gregorian?: number | null;
  birth_date_hijri?: number | null;
  death_date_gregorian?: string | null;
  death_date_hijri?: number | null;
  death_place?: string | null;
  full_name?: string | null;
  grade: string;
  name: string;
  parents?: string | null;
  scholar_indx?: number;
}
export interface Sources {
  book_source: string;
  content: string;
  id?: number;
  scholar_indx: number;
}
